### PR TITLE
bugfix: error if obfuscating empty file

### PR DESCRIPTION
**Pull request by sejans**

### CODE REVIEW

**Comment by sejans** [comment]
Its more than t2o month that noone is merging - whats wrong? The code I wrote - no feedback - I close this

**Comment by saltukalakus** [comment]
I observed same problem in liftoff:master. Why this is closed without merge?

**Comment by sejans** [comment]
because i waited for more than 2 month, and no one merged - also no feedback about bad code, so I didnt understood whats the problem and continued to solve problems in sejans fork instead

**Comment by sayak-brm** [comment]
Apparently the developer(liftoff) isn't developing PyMinifier any more.

**Pull request closed without merging**
